# Generated by Django 3.0.7 on 2020-09-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
